language: ruby
rvm:
- 2.2

cache: bundler
sudo: false

script: ./script/cibuild

after_success:
  - ./script/cideploy

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speedup for html-proofer
