title: The Obsidian
email: staff@obsidian.gg
description: > # this means to ignore newlines until "baseurl:"
  Minecraft Community for Serious Enthusiasts
baseurl: ""
url: "http://obsidian.gg"
discourse_url: https://forum.the-obsidian.com/

github_username: the-obsidian

# Build settings
markdown: kramdown
exclude: [vendor]
