title: The Obsidian
email: staff@obsidian.gg
description: >
  Minecraft Community for Serious Enthusiasts
baseurl: ""
url: "http://obsidian.gg"
discourse_url: https://forum.obsidian.gg/

github_username: the-obsidian

# Build settings
markdown: kramdown
exclude: [vendor]
