#!/usr/bin/env bash
set -e

(
  [[ "$TRAVIS_PULL_REQUEST" != "false" ]] &&
  [[ "$TRAVIS_BRANCH" != "master" ]] &&
  echo "Skipping deploy - this is not master" &&
  exit 0
)

cd _site

git init

git config user.name "${GH_USER}"
git config user.email "${GH_EMAIL}"

git add .
git commit -m "Deploy to GitHub Pages"

git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages > /dev/null 2>&1
