#!/usr/bin/env bash
set -e

exit 0

# check that TRAVIS_PULL_REQUEST is false and TRAVIS_BRANCH is master

cd _site

git init

git config user.name "${GH_USER}"
git config user.email "${GH_EMAIL}"

git add .
git commit -m "Deploy to GitHub Pages"

git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages > /dev/null 2>&1
